import { SITE_NAME } from '@/lib/constants/site'
import type { ArchiveHub } from './types'

export const productionsGenreHubs: ArchiveHub[] = [
    {
        slug: 'doramas-historicos-coreanos',
        kind: 'productions',
        filter: { genre: 'historico' },
        title: 'Doramas Históricos Coreanos (Sageuk)',
        shortTitle: 'Sageuk',
        description: 'Os melhores doramas históricos coreanos (sageuk) com perfis em português, elenco, plataformas e onde assistir.',
        intro: [
            'Os sageuks — dramas históricos coreanos — transportam o espectador para dinastias como Joseon e Goryeo com figurinos elaborados, tramas políticas e romances épicos que prendem do primeiro ao último episódio.',
            `A ${SITE_NAME} organiza os melhores sageuk cadastrados para que você encontre onde assistir, conheça o elenco e explore as histórias que moldaram a Coreia.`,
        ],
        keywords: ['doramas historicos coreanos', 'sageuk', 'drama joseon', 'dorama historico', 'historico coreano netflix', 'dynasty drama'],
        faq: [
            { question: 'O que é sageuk?', answer: 'Sageuk é o termo coreano para drama histórico. Esses dramas se passam em períodos como a Dinastia Joseon (1392–1897) ou Goryeo e combinam história, política, romance e, às vezes, fantasia.' },
            { question: 'Qual é o sageuk mais famoso?', answer: '"Mr. Sunshine", "Jewel in the Palace", "Six Flying Dragons" e "Kingdom" estão entre os mais aclamados. "Kingdom" popularizou o gênero globalmente na Netflix.' },
        ],
    },
    {
        slug: 'doramas-romanticos',
        kind: 'productions',
        filter: { genre: 'romance' },
        title: 'Doramas coreanos românticos',
        shortTitle: 'Doramas românticos',
        description: 'Descubra os melhores doramas românticos coreanos com sinopse, elenco, avaliação e onde assistir.',
        intro: [
            'Os romances coreanos definiram um gênero único no mundo: com OSTs inesquecíveis, química de elenco e histórias que equilibram drama e leveza de forma incomum.',
            `Este guia reúne produções coreanas de romance catalogadas na ${SITE_NAME}, com páginas em português para entender elenco, sinopse e onde assistir.`,
        ],
        keywords: ['doramas românticos', 'kdramas românticos', 'doramas de romance coreano', 'romance coreano netflix'],
        whatYouWillFind: `Aqui você encontra doramas românticos coreanos catalogados na ${SITE_NAME}, com sinopse em português, avaliação, elenco e informações sobre onde assistir — de grandes sucessos da Netflix a clássicos das emissoras coreanas.`,
        relatedSearches: [
            { label: 'Doramas na Netflix', href: '/guias/doramas-coreanos-netflix' },
            { label: 'Doramas de comédia', href: '/guias/doramas-comedia-coreanos' },
            { label: 'Melhores doramas', href: '/guias/melhores-doramas-de-todos-os-tempos' },
            { label: 'Doramas de fantasia', href: '/guias/doramas-fantasia-coreanos' },
        ],
        faq: [
            { question: 'O que faz um bom dorama romântico coreano?', answer: 'Um bom dorama romântico coreano combina química entre os protagonistas, um OST marcante, conflitos emocionais bem desenvolvidos e a famosa tensão lenta antes do casal se unir.' },
            { question: 'Qual plataforma tem mais doramas românticos?', answer: 'Netflix, Disney+ e Amazon Prime têm crescido muito no catálogo de K-Dramas românticos, mas plataformas asiáticas como Viki e Kocowa ainda têm os maiores acervos históricos.' },
            { question: 'Quais são os doramas românticos mais populares?', answer: '"Crash Landing on You", "Goblin", "My Love from the Star", "Business Proposal", "What\'s Wrong with Secretary Kim" e "Nevertheless" estão entre os mais assistidos do gênero no Brasil.' },
            { question: 'O que é "slow burn" nos doramas românticos?', answer: 'Slow burn é a tensão romântica que se constrói lentamente ao longo dos episódios, com o casal resistindo ao sentimento antes de ceder. É uma das características mais amadas dos K-Dramas e cria uma fidelização enorme ao longo da série.' },
            { question: 'Os doramas românticos têm final feliz?', answer: 'A maioria dos doramas românticos coreanos termina com final feliz. Porém, há exceções aclamadas com finais mais abertos ou melancólicos, como "My Mister" e "Nevertheless".' },
            { question: 'Tem doramas românticos mais curtos para quem está começando?', answer: 'Sim. Doramas como "Business Proposal" (12 eps), "Nevertheless" (10 eps) e "What\'s Wrong with Secretary Kim" (16 eps) são ótimas opções de entrada por serem mais curtos e leves.' },
        ],
    },
    {
        slug: 'doramas-terror-coreanos',
        kind: 'productions',
        filter: { genre: 'terror' },
        title: 'Doramas coreanos de terror',
        shortTitle: 'Doramas de terror',
        description: 'Os melhores doramas coreanos de terror e horror com sinopse, elenco, plataformas e avaliações em português.',
        intro: [
            'O terror coreano criou uma linguagem própria no entretenimento global — de "Kingdom" (zumbis em Joseon) a "Sweet Home" (criaturas urbanas), os K-Dramas de horror combinam medo genuíno com drama humano profundo.',
            `Este guia reúne produções coreanas de terror cadastradas na ${SITE_NAME} para ajudar você a encontrar o próximo dorama de arrepiar.`,
        ],
        keywords: ['doramas terror coreanos', 'kdramas horror', 'dorama coreano terror', 'horror coreano netflix', 'k-drama terror'],
        faq: [
            { question: 'O terror coreano é diferente do americano?', answer: 'Sim. O horror coreano costuma combinar susto com metáforas sociais, drama emocional e produção cinematográfica. "Train to Busan" e "Kingdom" são exemplos de como o gênero aborda temas humanos através do sobrenatural.' },
            { question: 'Quais são os melhores doramas de terror?', answer: '"Kingdom", "Sweet Home", "All of Us Are Dead" e "The Haunting of Villa Margarita" estão entre os mais elogiados da categoria nos últimos anos.' },
        ],
    },
    {
        slug: 'doramas-thriller-coreanos',
        kind: 'productions',
        filter: { genre: 'thriller' },
        title: 'Doramas coreanos de thriller',
        shortTitle: 'Doramas thriller',
        description: 'Os melhores doramas coreanos de thriller e suspense com sinopse, elenco, plataformas e avaliações em português.',
        intro: [
            'O thriller coreano é um dos gêneros mais elogiados pelos críticos internacionais — com reviravoltas calculadas, personagens complexos e atmosferas que mantêm a tensão do início ao fim.',
            `Este guia reúne produções coreanas de thriller e suspense cadastradas na ${SITE_NAME} para ajudar você a encontrar o próximo dorama que vai te deixar sem dormir.`,
        ],
        keywords: ['doramas thriller coreanos', 'kdramas suspense', 'dorama coreano thriller', 'suspense coreano netflix', 'k-drama mystery'],
        faq: [
            { question: 'O que torna os thrillers coreanos únicos?', answer: 'Os thrillers coreanos se destacam pela precisão narrativa, reviravoltas bem construídas e uma atenção ao detalhe psicológico que poucos países conseguem replicar. "Stranger", "Signal" e "My Name" são exemplos emblemáticos.' },
            { question: 'Onde assistir thrillers coreanos?', answer: 'Netflix tem a maior concentração de K-Dramas thriller com legendas em português. Disney+ e Viki também têm títulos de destaque no gênero.' },
        ],
    },
    {
        slug: 'doramas-acao-coreanos',
        kind: 'productions',
        filter: { genre: 'acao' },
        title: 'Doramas coreanos de ação',
        shortTitle: 'Doramas de ação',
        description: 'Os melhores doramas coreanos de ação com cenas de luta, espionagem, perseguição e avaliações em português.',
        intro: [
            'Os doramas de ação coreanos impressionam pela qualidade das cenas de luta, produção cinematográfica e histórias que misturam espionagem, crime e conflitos pessoais intensos.',
            `Este guia reúne produções coreanas de ação cadastradas na ${SITE_NAME} para ajudar você a encontrar o próximo dorama cheio de adrenalina.`,
        ],
        keywords: ['doramas ação coreanos', 'kdramas ação', 'dorama coreano espionagem', 'ação coreana netflix', 'k-drama action'],
        faq: [
            { question: 'Os doramas de ação coreanos têm cenas de qualidade cinematográfica?', answer: 'Sim. A indústria coreana investiu muito em coreografia de luta e produção de ação. Séries como "Bloodhounds", "Vincenzo" e "My Name" são exemplos de produção de nível cinema.' },
            { question: 'Qual é o melhor dorama de ação coreano?', answer: '"Vincenzo", "Bloodhounds", "My Name", "Doctor Slump" e "Gyeongseong Creature" estão entre os mais elogiados do gênero nos últimos anos.' },
        ],
    },
    {
        slug: 'doramas-comedia-coreanos',
        kind: 'productions',
        filter: { genre: 'comedia' },
        title: 'Doramas coreanos de comédia',
        shortTitle: 'Doramas de comédia',
        description: 'Os melhores doramas coreanos de comédia e comédia romântica com sinopse, elenco e avaliações em português.',
        intro: [
            'A comédia coreana tem um timing único: a mistura de constrangimento, humor físico e situações absurdas criou um estilo que fãs no mundo inteiro adoram e reconhecem imediatamente.',
            `Este guia reúne produções coreanas de comédia cadastradas na ${SITE_NAME} para ajudar você a encontrar o próximo dorama que vai fazer você rir e se sentir bem.`,
        ],
        keywords: ['doramas comedia coreanos', 'kdramas comédia', 'dorama coreano engraçado', 'comédia romântica coreana', 'k-drama comedy'],
        faq: [
            { question: 'O que caracteriza uma boa comédia coreana?', answer: 'As comédias coreanas são famosas pelo timing preciso, protagonistas excêntricos e situações de constrangimento que geram empatia. O gênero "romantic comedy" é especialmente popular com OSTs memoráveis.' },
            { question: 'Quais são os melhores doramas de comédia?', answer: '"My Love from the Star", "She Was Pretty", "Strong Woman Do Bong-soon" e "What\'s Wrong with Secretary Kim" estão entre os favoritos dos fãs de K-Drama comédia.' },
        ],
    },
    {
        slug: 'doramas-fantasia-coreanos',
        kind: 'productions',
        filter: { genre: 'fantasia' },
        title: 'Doramas coreanos de fantasia',
        shortTitle: 'Doramas de fantasia',
        description: 'Os melhores doramas coreanos de fantasia com magia, seres sobrenaturais e mundos paralelos em português.',
        intro: [
            'Os doramas de fantasia coreanos criam universos únicos — deuses, demônios, viagens no tempo e reinos mágicos — com produção visual impressionante e histórias que ficam na memória.',
            `Este guia reúne produções coreanas de fantasia cadastradas na ${SITE_NAME} para ajudar você a mergulhar em mundos além do real.`,
        ],
        keywords: ['doramas fantasia coreanos', 'kdramas fantasia', 'dorama coreano sobrenatural', 'fantasia coreana netflix', 'k-drama fantasy'],
        faq: [
            { question: 'O que torna os doramas de fantasia coreanos únicos?', answer: 'A fantasia coreana costuma misturar mitologia e folclore coreano com romance e drama humano. Criaturas como gumiho (raposa de nove caudas), dokkaeby e deuses do folclore coreano aparecem com frequência.' },
            { question: 'Quais são os melhores doramas de fantasia?', answer: '"Goblin", "Legend of the Blue Sea", "My Love from the Star", "Tale of the Nine-Tailed" e "Alchemy of Souls" estão entre os mais amados do gênero.' },
        ],
    },
    {
        slug: 'melhores-doramas-de-todos-os-tempos',
        kind: 'productions',
        filter: {},
        title: 'Melhores doramas coreanos de todos os tempos',
        shortTitle: 'Melhores doramas',
        description: 'Os doramas coreanos mais bem avaliados de todos os tempos com sinopse, elenco, plataformas e avaliações em português.',
        intro: [
            'Alguns K-Dramas transcenderam o momento do lançamento e se tornaram marcos culturais — assistidos e reassistidos por fãs ao redor do mundo há anos ou décadas.',
            `Este guia reúne as produções coreanas com melhor avaliação e maior impacto cultural cadastradas na ${SITE_NAME}, uma referência para quem quer começar ou aprofundar sua jornada no universo dos K-Dramas.`,
        ],
        keywords: ['melhores doramas coreanos', 'top kdramas', 'doramas imperdíveis', 'melhores k-dramas de todos os tempos', 'doramas classicos'],
        whatYouWillFind: 'Uma porta de entrada para explorar os doramas mais relevantes do catálogo: romances populares, thrillers, clássicos, séries por plataforma e produções por ano.',
        relatedSearches: [
            { label: 'Doramas para romance', href: '/guias/doramas-romanticos' },
            { label: 'Doramas na Netflix', href: '/guias/doramas-coreanos-netflix' },
            { label: 'Doramas 2026', href: '/guias/doramas-coreanos-2026' },
            { label: 'Doramas de thriller', href: '/guias/doramas-thriller-coreanos' },
            { label: 'Doramas de fantasia', href: '/guias/doramas-fantasia-coreanos' },
        ],
        faq: [
            { question: 'Qual é o melhor dorama coreano de todos os tempos?', answer: '"Goblin", "My Love from the Star", "Reply 1988", "Mr. Sunshine" e "Crash Landing on You" aparecem consistentemente nos rankings globais de melhores K-Dramas. A resposta varia por gênero e geração.' },
            { question: 'Por onde começar a assistir doramas coreanos?', answer: 'Para iniciantes, "Crash Landing on You" e "Goblin" são ótimas portas de entrada. Para quem prefere ação, "Vincenzo". Para romance puro, "My Love from the Star".' },
        ],
    },
    {
        slug: 'doramas-medicos-coreanos',
        kind: 'productions',
        filter: { tag: 'medico' },
        title: 'Doramas médicos coreanos',
        shortTitle: 'Doramas médicos',
        description: 'Os melhores doramas médicos coreanos com hospitais, cirurgias, romance, elenco e avaliações em português.',
        intro: [
            'Doramas médicos coreanos combinam casos hospitalares intensos, relações humanas e personagens que crescem sob pressão. É um dos subgêneros mais fortes para quem gosta de drama emocional com ritmo de série procedural.',
            `Este guia reúne produções coreanas médicas cadastradas na ${SITE_NAME} para facilitar a busca por sinopse, elenco, avaliação e títulos parecidos.`,
        ],
        keywords: ['doramas medicos coreanos', 'kdramas médicos', 'dorama hospital coreano', 'drama medico coreano'],
        whatYouWillFind: 'Doramas ambientados em hospitais, clínicas e equipes médicas, com casos de pacientes, romance, amizade, ética profissional e jornadas de superação.',
        relatedSearches: [
            { label: 'Doramas jurídicos', href: '/guias/doramas-juridicos-coreanos' },
            { label: 'Doramas familiares', href: '/guias/doramas-familia-coreanos' },
            { label: 'Doramas românticos', href: '/guias/doramas-romanticos' },
        ],
        faq: [
            { question: 'Quais temas aparecem em doramas médicos coreanos?', answer: 'Eles costumam misturar rotina hospitalar, dilemas éticos, amizade, romance e histórias de superação entre médicos, pacientes e famílias.' },
            { question: 'Doramas médicos são bons para começar em K-Drama?', answer: 'Sim. Muitos têm estrutura episódica fácil de acompanhar, mas também desenvolvem arcos emocionais longos e personagens memoráveis.' },
        ],
    },
    {
        slug: 'doramas-juridicos-coreanos',
        kind: 'productions',
        filter: { tag: 'juridico' },
        title: 'Doramas jurídicos coreanos',
        shortTitle: 'Doramas jurídicos',
        description: 'Doramas jurídicos coreanos com advogados, promotores, tribunais, investigação e dilemas morais.',
        intro: [
            'Doramas jurídicos coreanos costumam combinar casos de tribunal com drama humano, investigação e críticas sociais. O resultado são histórias com alto potencial de maratona e discussões morais fortes.',
            `Este guia reúne produções com temática jurídica no catálogo da ${SITE_NAME} — de dramas de tribunal a séries com promotores, advogados e investigadores.`,
        ],
        keywords: ['doramas juridicos coreanos', 'kdramas de advogado', 'doramas de tribunal', 'dorama promotor coreano', 'series coreanas juridicas'],
        whatYouWillFind: 'Produções com advogados, promotores, julgamentos, crimes, dilemas éticos e personagens ligados ao sistema de justiça coreano.',
        relatedSearches: [
            { label: 'Doramas policiais', href: '/guias/doramas-policiais-coreanos' },
            { label: 'Doramas de mistério', href: '/guias/doramas-misterio-coreanos' },
            { label: 'Doramas thriller', href: '/guias/doramas-thriller-coreanos' },
        ],
        faq: [
            { question: 'Doramas jurídicos coreanos são parecidos com séries policiais?', answer: 'Às vezes. A diferença é que o foco jurídico está em tribunais, advogados, promotores e consequências legais, enquanto o policial costuma priorizar investigação e ação de campo.' },
            { question: 'Esse tipo de dorama tem casos por episódio?', answer: 'Alguns seguem casos episódicos; outros desenvolvem um grande caso ao longo da temporada. Muitos misturam os dois formatos.' },
        ],
    },
    {
        slug: 'doramas-escolares-coreanos',
        kind: 'productions',
        filter: { tag: 'escola' },
        title: 'Doramas escolares coreanos',
        shortTitle: 'Doramas escolares',
        description: 'Doramas coreanos escolares e universitários com romance, amizade, bullying, juventude e amadurecimento.',
        intro: [
            'Doramas escolares coreanos são uma das portas de entrada mais populares para K-Drama: eles misturam amizade, primeiro amor, rivalidade, pressão por notas e conflitos familiares.',
            `Este guia organiza produções marcadas com temática escolar no catálogo da ${SITE_NAME}, facilitando a busca por histórias de juventude e amadurecimento.`,
        ],
        keywords: ['doramas escolares coreanos', 'kdramas escolares', 'doramas de escola', 'dorama colegial coreano', 'doramas universitarios coreanos'],
        whatYouWillFind: 'Produções com ambiente escolar, universidade, amadurecimento, romance jovem, grupos de amigos e conflitos típicos da juventude coreana.',
        relatedSearches: [
            { label: 'Doramas românticos', href: '/guias/doramas-romanticos' },
            { label: 'Doramas de comédia', href: '/guias/doramas-comedia-coreanos' },
            { label: 'Idols que atuam', href: '/guias/idols-que-atuam-em-doramas' },
        ],
        faq: [
            { question: 'O que caracteriza um dorama escolar coreano?', answer: 'Geralmente são histórias centradas em estudantes, escolas ou universidades, com temas como amizade, bullying, pressão acadêmica, primeiro amor e amadurecimento.' },
            { question: 'Doramas escolares são só romance?', answer: 'Não. Muitos têm romance, mas o subgênero também aparece em suspense, fantasia, drama familiar, comédia e histórias sobre saúde mental ou rivalidade acadêmica.' },
        ],
    },
    {
        slug: 'doramas-familia-coreanos',
        kind: 'productions',
        filter: { tag: 'familia' },
        title: 'Doramas coreanos sobre família',
        shortTitle: 'Doramas de família',
        description: 'Doramas coreanos sobre família, relações entre gerações, reconciliação, herança, casamento e laços afetivos.',
        intro: [
            'Família é um dos temas mais fortes dos K-Dramas: pais e filhos, irmãos, avós, casamentos, segredos antigos e reconciliações aparecem em romances, melodramas e comédias.',
            `Este guia reúne produções coreanas com foco familiar no catálogo da ${SITE_NAME} para quem gosta de histórias emocionais e personagens em transformação.`,
        ],
        keywords: ['doramas familia coreanos', 'kdramas familia', 'doramas sobre família', 'drama familiar coreano', 'doramas emocionantes coreanos'],
        whatYouWillFind: 'Produções com relações familiares, conflitos entre gerações, segredos, reconciliações, casamentos e dilemas afetivos.',
        relatedSearches: [
            { label: 'Doramas médicos', href: '/guias/doramas-medicos-coreanos' },
            { label: 'Doramas românticos', href: '/guias/doramas-romanticos' },
            { label: 'Doramas de comédia', href: '/guias/doramas-comedia-coreanos' },
        ],
        faq: [
            { question: 'Doramas familiares são sempre longos?', answer: 'Nem sempre. Existem dramas familiares longos de TV aberta, mas também doramas de 12 a 16 episódios em que a família é um eixo emocional importante.' },
            { question: 'Esse guia inclui romance familiar?', answer: 'Sim. Muitos K-Dramas misturam romance e família, especialmente quando casamento, parentes, herança ou aprovação familiar fazem parte do conflito.' },
        ],
    },
    {
        slug: 'doramas-esportes-coreanos',
        kind: 'productions',
        filter: { tag: 'esportes' },
        title: 'Doramas coreanos de esportes',
        shortTitle: 'Doramas de esportes',
        description: 'Doramas coreanos de esportes com competição, superação, juventude, trabalho em equipe e romance.',
        intro: [
            'Doramas esportivos coreanos costumam usar competição como linguagem para falar de disciplina, amizade, pressão, fracasso e recomeço.',
            `Este guia reúne produções com temática de esporte no catálogo da ${SITE_NAME}, ideal para quem gosta de histórias de superação e energia juvenil.`,
        ],
        keywords: ['doramas esportes coreanos', 'kdramas esportivos', 'doramas de esporte', 'dorama coreano competição', 'doramas de superação coreanos'],
        whatYouWillFind: 'Histórias com atletas, equipes, torneios, treinadores, rivalidades, juventude e superação dentro ou ao redor do esporte.',
        relatedSearches: [
            { label: 'Doramas escolares', href: '/guias/doramas-escolares-coreanos' },
            { label: 'Doramas românticos', href: '/guias/doramas-romanticos' },
            { label: 'Doramas de ação', href: '/guias/doramas-acao-coreanos' },
        ],
        faq: [
            { question: 'Doramas de esportes são só sobre competição?', answer: 'Não. A competição costuma ser o cenário, mas o centro geralmente é amadurecimento, amizade, romance, pressão psicológica e superação.' },
            { question: 'Esse guia inclui romances esportivos?', answer: 'Sim. Quando a produção está marcada com esportes, ela pode aparecer mesmo misturando romance, juventude ou comédia.' },
        ],
    },
    {
        slug: 'doramas-culinaria-coreanos',
        kind: 'productions',
        filter: { tag: 'culinaria' },
        title: 'Doramas coreanos de culinária',
        shortTitle: 'Doramas de culinária',
        description: 'Doramas coreanos de culinária, restaurantes, chefs, comida coreana, romance e histórias afetivas ao redor da mesa.',
        intro: [
            'Comida em K-Drama quase nunca é só comida: ela marca encontros, reconciliações, memórias familiares e o conforto emocional que muitas histórias coreanas sabem construir tão bem.',
            `Este guia reúne produções com culinária, chefs, restaurantes e comida coreana no catálogo da ${SITE_NAME}.`,
        ],
        keywords: ['doramas culinaria coreanos', 'kdramas comida', 'doramas sobre chefs', 'dorama restaurante coreano', 'comida coreana dorama'],
        whatYouWillFind: 'Produções com restaurantes, chefs, receitas, comida coreana, romance gastronômico e histórias afetivas ligadas à culinária.',
        relatedSearches: [
            { label: 'Doramas de família', href: '/guias/doramas-familia-coreanos' },
            { label: 'Doramas românticos', href: '/guias/doramas-romanticos' },
            { label: 'Doramas de comédia', href: '/guias/doramas-comedia-coreanos' },
        ],
        faq: [
            { question: 'Doramas de culinária são leves?', answer: 'Muitos têm tom leve ou romântico, mas o tema também pode aparecer em dramas familiares, histórias de superação e narrativas sobre trabalho.' },
            { question: 'Esse guia ajuda a descobrir comida coreana?', answer: 'Sim. Além da trama, muitos doramas de culinária apresentam pratos, restaurantes e hábitos alimentares coreanos que despertam curiosidade sobre a cultura.' },
        ],
    },
    {
        slug: 'doramas-policiais-coreanos',
        kind: 'productions',
        filter: { genre: 'crime' },
        title: 'Doramas policiais coreanos',
        shortTitle: 'Doramas policiais',
        description: 'Doramas policiais coreanos com investigação, crime, detetives, promotores e suspense em português.',
        intro: [
            'Doramas policiais coreanos se destacam por investigações complexas, crimes em camadas e personagens que enfrentam corrupção, traumas e dilemas morais.',
            `Este guia reúne produções coreanas de investigação, crime e polícia cadastradas na ${SITE_NAME} para quem quer histórias tensas e bem amarradas.`,
        ],
        keywords: ['doramas policiais coreanos', 'kdramas policiais', 'dorama coreano investigação', 'crime coreano série'],
        whatYouWillFind: 'Histórias de investigação, crime, delegacias, promotores, detetives e suspense criminal, com links para produções e artistas relacionados.',
        relatedSearches: [
            { label: 'Doramas jurídicos', href: '/guias/doramas-juridicos-coreanos' },
            { label: 'Doramas de mistério', href: '/guias/doramas-misterio-coreanos' },
            { label: 'Doramas thriller', href: '/guias/doramas-thriller-coreanos' },
        ],
        faq: [
            { question: 'Doramas policiais coreanos são parecidos com thrillers?', answer: 'Muitas vezes sim, mas o hub policial prioriza investigação, delegacias, promotores, crimes e detetives como eixo principal da história.' },
            { question: 'O hub inclui séries de serial killer?', answer: 'Pode incluir quando a produção está marcada com crime, investigação, thriller policial ou temas semelhantes no catálogo.' },
        ],
    },
    {
        slug: 'doramas-misterio-coreanos',
        kind: 'productions',
        filter: { genre: 'misterio' },
        title: 'Doramas coreanos de mistério',
        shortTitle: 'Doramas de mistério',
        description: 'Doramas coreanos de mistério com enigmas, segredos obscuros, detetives particulares e tramas que prendem do começo ao fim.',
        intro: [
            'Doramas de mistério coreanos são uma das categorias mais viciantes do gênero: cada episódio traz novas pistas, revelações e giros que deixam o espectador preso à tela.',
            'Do assassino em série à conspiração corporativa, do paranormal ao thriller psicológico — o K-Drama de mistério oferece uma variedade enorme de premissas e atmosferas.',
            `Este guia organiza produções coreanas com mistério, enigmas e narrativas de investigação cadastradas na ${SITE_NAME}.`,
        ],
        keywords: ['doramas misterio coreanos', 'kdramas misterio', 'dorama misterio', 'doramas enigma coreano', 'dorameiros misterio'],
        faq: [
            { question: 'O que define um dorama de mistério?', answer: 'Um dorama de mistério tem no centro um segredo, enigma ou crime que precisa ser resolvido ao longo da história. Pode misturar romance, terror ou thriller na trama principal.' },
            { question: 'Doramas de mistério costumam ter final revelador?', answer: 'A maioria tem sim, embora alguns deixem pontas soltas propositalmente. O K-Drama de mistério é conhecido por giros de roteiro e revelações no final dos episódios.' },
            { question: 'Mistério e thriller são a mesma coisa em doramas?', answer: 'Não exatamente. Thriller foca em tensão e perigo iminente; mistério foca em descobrir a verdade por trás de algo oculto. Muitos K-Dramas misturam os dois.' },
        ],
    },
    {
        slug: 'doramas-sobrevivencia-coreanos',
        kind: 'productions',
        filter: { genre: 'thriller' },
        title: 'Doramas coreanos de sobrevivência',
        shortTitle: 'Doramas de sobrevivência',
        description: 'Doramas coreanos de sobrevivência, apocalipse, pandemia, game show de vida ou morte e lutas extremas pela existência.',
        intro: [
            '"Squid Game" popularizou globalmente o conceito de survival game coreano — mas o K-Drama trabalha esse tema muito antes, com produções que exploram sobrevivência em sentidos literal e metafórico.',
            `Este guia reúne produções coreanas com sobrevivência, jogo de vida ou morte, apocalipse e situações extremas catalogadas na ${SITE_NAME}.`,
        ],
        keywords: ['doramas sobrevivencia coreanos', 'kdramas survival', 'squid game tipo', 'doramas apocalipse coreano', 'survival game dorama'],
        faq: [
            { question: 'Doramas de sobrevivência são sempre violentos?', answer: 'Nem sempre. Alguns são mais psicológicos, focados em dilemas morais e decisões extremas. O nível de violência varia bastante entre os títulos.' },
            { question: 'Quais são os melhores doramas de sobrevivência?', answer: '"Squid Game", "Sweet Home", "All of Us Are Dead", "Hellbound" e "The Silent Sea" são destaques do subgênero de sobrevivência e apocalipse coreano.' },
        ],
    },
    {
        slug: 'filmes-coreanos',
        kind: 'productions',
        filter: { type: 'movie' },
        title: 'Filmes coreanos',
        shortTitle: 'Filmes coreanos',
        description: 'Filmes coreanos com sinopse, elenco, avaliação e páginas relacionadas em português.',
        intro: [
            'O cinema coreano vai muito além dos doramas: thrillers, romances, ação, horror e dramas autorais ajudaram a consolidar a Coreia como potência audiovisual.',
            `Este guia reúne filmes coreanos cadastrados na ${SITE_NAME} para navegar por sinopse, elenco, avaliação e artistas relacionados.`,
        ],
        keywords: ['filmes coreanos', 'cinema coreano', 'k-movies', 'filme coreano onde assistir'],
        faq: [
            { question: 'Este guia inclui apenas doramas?', answer: 'Não. Diferente dos guias de K-Drama, este é dedicado a filmes coreanos cadastrados como produções de cinema.' },
            { question: 'As páginas mostram elenco?', answer: 'Quando sincronizado, cada filme pode mostrar elenco, artistas relacionados, avaliação e outros dados editoriais.' },
        ],
    },
]
